/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   date-validator.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../iron-validator-behavior/iron-validator-behavior.d.ts" />

interface DateValidatorElement extends Polymer.Element, Polymer.IronValidatorBehavior {
  validate(date: any): any;
}

interface HTMLElementTagNameMap {
  "date-validator": DateValidatorElement;
}
