/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   gold-cc-expiration-input.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../paper-input/paper-input-behavior.d.ts" />
/// <reference path="../paper-input/paper-input-container.d.ts" />
/// <reference path="../paper-input/paper-input-error.d.ts" />
/// <reference path="../iron-input/iron-input.d.ts" />
/// <reference path="../iron-form-element-behavior/iron-form-element-behavior.d.ts" />
/// <reference path="date-input.d.ts" />

/**
 * `gold-cc-expiration-input` is a  single-line text field with Material Design styling
 * for entering a credit card's expiration date
 *
 *     <gold-cc-expiration-input></gold-cc-expiration-input>
 *     <gold-cc-expiration-input value="11/15"></gold-cc-expiration-input>
 *
 * It may include an optional label, which by default is "Expiration Date".
 *
 *     <gold-cc-expiration-input label="Date"></gold-cc-expiration-input>
 *
 *
 * ### Validation
 *
 * The input can check whether the entered date is a valid, future date.
 *
 * The input can be automatically validated as the user is typing by using
 * the `auto-validate` and `required` attributes. For manual validation, the
 * element also has a `validate()` method, which returns the validity of the
 * input as well sets any appropriate error messages and styles.
 *
 * See `Polymer.PaperInputBehavior` for more API docs.
 *
 * ### Styling
 *
 * See `Polymer.PaperInputContainer` for a list of custom properties used to
 * style this element.
 */
interface GoldCcExpirationInputElement extends Polymer.Element, Polymer.PaperInputBehavior, Polymer.IronFormElementBehavior {

  /**
   * The label for this input.
   */
  label: string|null|undefined;
  value: string|null|undefined;

  /**
   *  The underlying dateInput is tabbable 
   */
  hostAttributes: object|null;
  ready(): void;
  created(): void;

  /**
   * Overidden from Polymer.PaperInputBehavior.
   */
  validate(): any;

  /**
   * A handler that is called on input
   */
  _onValueChanged(value: any, oldValue: any): void;
  _dateChanged(event: any): void;
  _computeMonth(value: any): any;
  _computeYear(value: any): any;

  /**
   * Overidden from Polymer.IronControlState.
   */
  _onFocusedChanged(focused: any): void;
}

interface HTMLElementTagNameMap {
  "gold-cc-expiration-input": GoldCcExpirationInputElement;
}
